plink_genotype_file: None
illumina_manifest_file: /DCEG/CGF/Infinium/Resources/Manifests/GSAMD-Files/build37/GSAMD-24v1-0_20011747_A1.bpm
snp_cr_1: 0.8
samp_cr_1: 0.8
snp_cr_2: 0.95
samp_cr_2: 0.95
ld_prune_r2: 0.1
maf_for_ibd: 0.2
sample_sheet: /DCEG/CGF/Infinium/SampleSheets/SR0446-001_57_AnalysisManifest_MERGED_Batch1_20_and_21.csv
subject_id_to_use: PI_Subject_ID
ibd_pi_hat_cutoff: 0.95
dup_concordance_cutoff: 0.95
expected_sex_col_name: Expected_Sex
num_samples: 90232
lims_output_dir: /DCEG/CGF/Bioinformatics/Production/Jiahui/FogbugzCase/Case24856/
contam_threshold: 0.2
adpc_file: None
gtc_dir: None
remove_contam: "YES"
remove_sex_discordant: "YES"
remove_rep_discordant: "YES"
remove_unexpected_rep: "YES"
pi_hat_threshold: 0.2
autosomal_het_thresh: 0.1
minimum_pop_subjects: 50
control_hwp_thresh: 50
doc_template: /DCEG/CGF/Bioinformatics/Production/Eric/refFiles/GwasQcPipeline_Template_interim.docx
contam_pop: AF
strand: TOP
start_time: Fri Oct 18 15:38:11 2019
numSNPs: 700078
