# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"  
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.5
      with:
        # Whether to activate the conda base env (Default: 'true')
        activate-conda: true
        # If conda should be updated before running other commands (Default: 'false')
        update-conda: true
        # Python version which should be installed with conda (default: 'Default')
        python-version: ${{ matrix.python-version }}
        # Additional channels like 'conda-forge' which can be used to install packages
        conda-channels: conda-forge, bioconda, default
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        poetry run pytest
